player = MusicPlayer()
player.play()   # Starting the music...
player.pause()  # Pausing the music...
player.stop()   # Stopping the music...
player.play()   # Starting the music...
player.stop()   # Stopping the music...
